name: Publish Docker image

on:
  push:
    branches:
      - master

jobs:
  Deploy-to-production:
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: pcoker581
          password: dckr_pat_b2GQsgfKvBLR2WB-LsC_LIxPxzQ
      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pcoker581/front-youslot:production
      - name: Pull Docker Image In Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull pcoker581/front-youslot:production
            docker container stop front-rtp
            docker container rm front-rtp
            docker container create --name front-rtp -p 3000:3000 --restart=always pcoker581/front-youslot:production
            docker network connect mynet front-rtp
            docker container start front-rtp
